version: '3.1'

###### NOTICE ######
# Most services have their ports exposed.
# This is for testing only and should be removed
# before final release.

networks:
    app-net:
        driver: bridge

volumes:
    mongo:

services:
    # MQTT Broker
    mosquitto:
        container_name: service.mqtt
        image: eclipse-mosquitto
        ports:
            - "1883:1883"
            - "9001:9001"
        networks:
            - app-net
    
    # Database
    mongo:
        container_name: service.mongo
        image: mongo
        ports:
            - 27017:27017
        volumes:
            - mongo:/data/db
            - ./service.ledger/mongo:/docker-entrypoint-initdb.d
        environment: 
            - MONGO_INITDB_DATABASE=ggrm
        networks:
            - app-net

    # Gateway
    # nginx:
    #     container_name: service.gateway
    #     image: nginx
    #     volumes: 
    #         - ./conf/nginx.conf:/etc/nginx/nginx.conf
    #     ports:
    #         - 80:80

    # -- services --

    config:
        container_name: service.configuration
        build: ./service.config
        ports:
            - "3000:3000"
        networks:
            - app-net
